### ISSUE TITLE
'IndexError: list index out of range' error when typing words.

### ISSUE THREAD

**Issue by piyush-jaiswal** [nvs-abhilash/CorrectMe#24]
We sometimes get this error in the terminal when typing in words. Using the suggestions when this error pops up sometimes works, other times makes the program crash.

**Comment by nvs-abhilash** [comment]
Can you find a reproducible example for this error? That would be helpful for debugging it in the future.

**Comment by piyush-jaiswal** [comment]
Simply typing gibberish words like 'asdas' should reproduce the issue.

**Comment by piyush-jaiswal** [comment]
Fixed by #26.
